import { readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { resolve, basename } from "node:path";
import { spawn } from "node:child_process";
import { parse as parseYaml } from "yaml";

export type DeployProvider = "fly";

export interface DeployOptions {
  cwd?: string;
  provider?: DeployProvider;
  appName?: string;
  region?: string;
  configFile?: string;
  force?: boolean;
  launch?: boolean;
  flyctl?: string;
}

export interface DeployResult {
  appName: string;
  region: string;
  filesWritten: string[];
  filesSkipped: string[];
  nextSteps: string[];
  launched: boolean;
}

const APP_NAME_RE = /^[a-z0-9][a-z0-9-]{0,29}$/;
const DEFAULT_REGION = "ams";

export function deriveAppName(projectDir: string): string {
  const base = basename(resolve(projectDir));
  const slug = base
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 30);
  if (!slug) {
    throw new Error(
      `cannot derive a Fly app name from directory "${base}" — pass --app-name explicitly`,
    );
  }
  return slug;
}

export function validateAppName(name: string): void {
  if (!APP_NAME_RE.test(name)) {
    throw new Error(
      `invalid Fly app name "${name}" — use 1-30 lowercase letters, digits, and hyphens (start with a letter or digit)`,
    );
  }
}

export function dockerfileContents(): string {
  return `# Generated by \`x402-kit deploy\`. Edit freely; rerun with --force to regenerate.
FROM node:22-bookworm-slim AS build
WORKDIR /app
COPY package.json package-lock.jso[n] ./
RUN npm install --omit=dev --no-audit --no-fund \\
 || (echo "no package-lock.json — falling back to npm install" && npm install --omit=dev --no-audit --no-fund)
COPY . .
RUN if [ -f tsconfig.json ]; then npx --yes tsc -p tsconfig.json; fi

FROM node:22-bookworm-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3402
COPY --from=build /app /app
RUN mkdir -p /data && chown -R node:node /app /data
USER node
VOLUME ["/data"]
EXPOSE 3402
CMD ["node", "dist/server.js"]
`;
}

export function flyTomlContents(appName: string, region: string): string {
  return `# Generated by \`x402-kit deploy\`.
# Deploy:
#   flyctl launch --copy-config --no-deploy   # first time only
#   flyctl deploy

app = "${appName}"
primary_region = "${region}"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3402"

[[mounts]]
  source = "x402_data"
  destination = "/data"

[http_service]
  internal_port = 3402
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
`;
}

export function dockerignoreContents(): string {
  return `node_modules
.git
.gitignore
*.db
*.db-journal
.env
.DS_Store
dist
.cache
`;
}

interface FileSpec {
  path: string;
  contents: string;
}

async function writeFiles(
  cwd: string,
  files: FileSpec[],
  force: boolean,
): Promise<{ written: string[]; skipped: string[] }> {
  const written: string[] = [];
  const skipped: string[] = [];
  for (const f of files) {
    const full = resolve(cwd, f.path);
    if (existsSync(full) && !force) {
      skipped.push(f.path);
      continue;
    }
    await writeFile(full, f.contents, "utf8");
    written.push(f.path);
  }
  return { written, skipped };
}

async function runFlyctl(
  flyctl: string,
  cwd: string,
  args: string[],
): Promise<number> {
  return new Promise((res, rej) => {
    const p = spawn(flyctl, args, { cwd, stdio: "inherit" });
    p.on("error", rej);
    p.on("exit", (code) => res(code ?? 1));
  });
}

export async function deploy(opts: DeployOptions = {}): Promise<DeployResult> {
  const cwd = opts.cwd ?? process.cwd();
  const provider = opts.provider ?? "fly";
  if (provider !== "fly") {
    throw new Error(`unsupported provider "${provider}" — only "fly" is supported`);
  }

  const configFile = opts.configFile ?? "x402-kit.yaml";
  const configPath = resolve(cwd, configFile);
  if (!existsSync(configPath)) {
    throw new Error(
      `config file not found at "${configPath}" — run \`x402-kit init <name>\` first or pass --config-file <path>`,
    );
  }

  const yamlSrc = await readFile(configPath, "utf8");
  let yamlDoc: unknown;
  try {
    yamlDoc = parseYaml(yamlSrc);
  } catch (err) {
    throw new Error(
      `failed to parse "${configFile}" as YAML: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
  if (!yamlDoc || typeof yamlDoc !== "object") {
    throw new Error(`"${configFile}" did not parse to an object`);
  }

  const appName = opts.appName ?? deriveAppName(cwd);
  validateAppName(appName);
  const region = opts.region ?? DEFAULT_REGION;

  const files: FileSpec[] = [
    { path: "Dockerfile", contents: dockerfileContents() },
    { path: "fly.toml", contents: flyTomlContents(appName, region) },
    { path: ".dockerignore", contents: dockerignoreContents() },
  ];

  const { written, skipped } = await writeFiles(cwd, files, Boolean(opts.force));

  const nextSteps: string[] = [];
  let launched = false;

  if (opts.launch) {
    const flyctl = opts.flyctl ?? "flyctl";
    const code = await runFlyctl(flyctl, cwd, [
      "launch",
      "--copy-config",
      "--no-deploy",
      "--name",
      appName,
      "--region",
      region,
    ]);
    if (code !== 0) {
      throw new Error(
        `flyctl exited with code ${code} — check that you're authenticated (\`flyctl auth login\`) and the app name "${appName}" is available`,
      );
    }
    const deployCode = await runFlyctl(flyctl, cwd, ["deploy"]);
    if (deployCode !== 0) {
      throw new Error(`flyctl deploy exited with code ${deployCode}`);
    }
    launched = true;
    nextSteps.push(`live at https://${appName}.fly.dev/`);
    nextSteps.push(`metrics at https://${appName}.fly.dev/__x402/metrics`);
  } else {
    nextSteps.push(`flyctl auth login           # one-time, opens browser`);
    nextSteps.push(`flyctl launch --copy-config --no-deploy --name ${appName} --region ${region}`);
    nextSteps.push(`flyctl deploy`);
    nextSteps.push(`# or rerun with --launch to do the above three for you`);
  }

  return { appName, region, filesWritten: written, filesSkipped: skipped, nextSteps, launched };
}
